// Autogenerated using cbuild
System.config({
	map: {
		"bluebird": "node_modules/bluebird"
	},
	meta: {
		"node_modules/*": { globals: { process: "node_modules/cbuild/process-dev.js" } }
	},
	packages: {
		"bluebird": {
			main: "js/browser/bluebird.js"
		}
	}
});
